
image: node:20

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install typescript --save-dev

build_project:
  stage: build
  script:
    - npm run build
deploy:
  stage: deploy
  script:
    - ssh ubuntu@YOUR_EC2_IP "cd ~/successmakerz && git pull origin main && npm install && npm run build && sudo cp -r dist/* /var/www/html/ && sudo systemctl restart nginx"


